### PR TITLE
feat: handle the previous modification

### PR DESCRIPTION
**Pull request by xiyaowong**
see commit message for details

### CODE REVIEW

**Comment by xiyaowong** [comment]
@max397574 I think `keys_before_delete` is not useful. Would you mind removing it?

**Comment by max397574** [comment]
ig you can remove it @xiyaowong

**Comment by xiyaowong** [comment]
Trialed this plugin last year, but didn't use it all the time. I recently saw this plugin again on reddit and intend to use it so that we can optimize it together. This pr mainly solves the problem of modifying the status that has been there before. And simplify the logic as much as possible @max397574

**Comment by max397574** [comment]
looks good to me
I still hadn't much experience when I did this plugin and I've never found the time to do a big refactor

**Comment by max397574** [comment]
just one thing
could you format with shiftwidth 4 before I merge?

**Comment by xiyaowong** [comment]
I use stylua to format code, you had provide stylua.toml 🤔

**Comment by max397574** [comment]
you could create one
```toml
column_width = 80
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferDouble"
no_call_parentheses = false
```

**Comment by xiyaowong** [comment]
@max397574 done

**Comment by xiyaowong** [comment]
could you review and merge it? @max397574

**Comment by max397574** [comment]
lgtm

**Pull request merged**
