### PR TITLE
refactor: rewrite to use mappings (for most modes)

### PR DESCRIPTION
**Pull request by Sam-programs**
Operator-pending mode still doesn't work, because i am not sure how it's supposed to work.
I added comments starting with `WIP:` for things that still need discussion.
Fix: #58
Fix: #46
Fix: #49

### CODE REVIEW

**Comment by Sam-programs** [comment]
Fix: #58
Fix: #46
Fix: #49

**Comment by max397574** [comment]
I'm also currently rewriting this on a branch here in the repo
I don't currently have time to work on it nor to review this pr properly
so for now I wouldn't spend too much time working on this because perhaps I'll rather use my implementation

**Comment by max397574** [comment]
@Sam-programs I added some changes to this pr
would it be okay to merge this from your side?

**Comment by Sam-programs** [comment]
> @Sam-programs I added some changes to this pr
would it be okay to merge this from your side?

Your changes LGTM, but I think i should change the `expr`-mappings to `feedkeys` calls. Because right now functions need to `vim.schedule` code that modifies the buffer. e.g:
```lua
        vim.schedule(function()
            vim.api.nvim_set_current_line("")
        end
```

**Comment by max397574** [comment]
closes https://github.com/max397574/better-escape.nvim/issues/23

**Comment by max397574** [comment]
Thank you very much for this contribution

**Pull request merged**
